// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMWwq84i_huhIQ67BfDEB2iHWC_DjOfeE',
    appId: '1:325757168020:web:769020641b63cb51fc8781',
    messagingSenderId: '325757168020',
    projectId: 'tracker-3d20a',
    authDomain: 'tracker-3d20a.firebaseapp.com',
    storageBucket: 'tracker-3d20a.appspot.com',
    measurementId: 'G-3FBQQ0NMGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxRNgtxP-BF8oYuj2_eWqJrNOD2lWACJ4',
    appId: '1:325757168020:android:54482cbf75da8321fc8781',
    messagingSenderId: '325757168020',
    projectId: 'tracker-3d20a',
    storageBucket: 'tracker-3d20a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS6UBvGtPTRnCWrHtKr_lzFQZ5JNn-9rg',
    appId: '1:325757168020:ios:0960df6edbc26829fc8781',
    messagingSenderId: '325757168020',
    projectId: 'tracker-3d20a',
    storageBucket: 'tracker-3d20a.appspot.com',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS6UBvGtPTRnCWrHtKr_lzFQZ5JNn-9rg',
    appId: '1:325757168020:ios:519b9d9d4b07bc6afc8781',
    messagingSenderId: '325757168020',
    projectId: 'tracker-3d20a',
    storageBucket: 'tracker-3d20a.appspot.com',
    iosBundleId: 'com.example.tracker.RunnerTests',
  );
}
